name: deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    uses: gramLabs/.github/workflows/main-go.yaml@main
    with:
      ssh-private-key: ${{ secrets.key }}
      ghcr-username: jgustie
      ghcr-password: ${{ secrets.PAT }}
