name: deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: gramLabs/.github/workflows/main-go@main
      with:
        ssh-private-key: ${{ secrets.key }}
        ghcr-username: jgustie
        ghcr-password: ${{ secrets.PAT }}
