name: Main
on:
  push:
    branches:
    - main

jobs:
  go:
    name: Go
    uses: gramLabs/.github/.github/workflows/main-go.yaml@main
    secrets:
      ssh-private-key: ${{ secrets.key }}
      ghcr-username: jgustie
      ghcr-password: ${{ secrets.PAT }}
