name: Pull Request
on:
  pull_request:
    branches:
    - main

jobs:
  go:
    name: Go
    uses: gramLabs/.github/.github/workflows/pull-request-go.yaml@main
    secrets:
      ssh-private-key: ${{ secrets.key }}
