name: Release Published
on:
  release:
    types:
    - published

jobs:
  docs:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Docs
      uses: actions/checkout@v3
      with:
        repository: jgustie/test-docs

    # https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: Download Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release download '${{ github.event.release.tag_name }}' -d './bin' -p '*_linux_amd64.tar.gz'
        cd bin && tar xf *.tar.gz && rm *.tar.gz && echo "$PWD" >> $GITHUB_PATH

    - name: Update content
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GH_REPO: jgustie/test-docs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b 'releases/${{ github.event.release.tag_name }}'

        hugo new 'posts/${{ github.event.release.tag_name }}.md'
        test-deploy >> 'content/posts/${{ github.event.release.tag_name }}.md'
        cat << EOF >> 'posts/${{ github.event.release.tag_name }}.md'

        ${{ github.event.release.body }}
        EOF

        git add content/posts
        git commit -m 'test-deploy ${{ github.event.release.tag_name }}' -m 'Updates the documentation for the new release'
        git push origin HEAD
        gh pr create --fill

