name: Release Published
on:
  release:
    types:
    - published

jobs:
  docs:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Docs
      uses: actions/checkout@v3
      with:
        repository: jgustie/test-docs
        token: ${{ secrets.PAT }}

    # https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: Download Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh release download '${{ github.event.release.tag_name }}' --dir './bin' --pattern '*_linux_amd64.tar.gz'
        cd bin && tar xf *.tar.gz && rm *.tar.gz && echo "$PWD" >> $GITHUB_PATH

    - name: Update content
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        GH_REPO: jgustie/test-docs
        FILENAME: posts/${{ github.event.release.tag_name }}.md
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b 'test-deploy-${{ github.event.release.tag_name }}'

        hugo new "$FILENAME"
        test-deploy >> "./content/$FILENAME"
        cat << EOF >> "./content/$FILENAME"
        ${{ github.event.release.body }}
        EOF
        git add "./content/$FILENAME"

        git commit -m 'test-deploy ${{ github.event.release.tag_name }}'
        git push origin HEAD
        gh pr create --fill
