name: Test WDandPush
on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      foobar:
        description: Does this always default?
        required: false
        default: 'Hello'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "${{ inputs.foobar }}, World!"
