name: Such Custom Name
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag
        required: true

jobs:
  echo:
    name: "Echo for ${{ github.event.inputs.tag_name }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Do echoing"
      run: |
        echo 'The summary is...' > $GITHUB_STEP_SUMMARY
        echo '${{ github.event.inputs.tag_name }}'
    - name: "Do more echoing"
      run: |
        echo 'More summary is' >> $GITHUB_STEP_SUMMARY
