name: Such Custom Name
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag
        required: true

jobs:
  echo:
    name: "Echo for ${{ github.event.inputs.tag_name }}"
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ github.event.inputs.tag_name }}'
